### ISSUE TITLE
中文语音输入的文字有空格！

### ISSUE THREAD

**Issue by dsssok** [ElishaAz/Sayboard#22] opened 2023-03-29 15:00 UTC
字体 间 有 空格，应该 把 空格 去 除掉！

**Comment by ElishaAz** [comment] 2023-03-29 15:15
Sorry, I do not speak Chinese.
Google translate translated it as
> The text input by Chinese voice has spaces!
> There are spaces between fonts, the spaces should be removed!

Which means this is a duplicate of #16

**Closed by ElishaAz** 2023-03-29 15:15 UTC

**Comment by dsssok** [comment] 2023-03-30 15:07
> 對不起，我不會說中文。 谷歌翻譯將其翻譯為
> 
> > 中文語音輸入的文字有空格！
> > 字體之間有空格，空格要去掉！
> 
> [這意味著這是#16](https://github.com/ElishaAz/Sayboard/issues/16)的副本[](https://github.com/ElishaAz/Sayboard/issues/16)

In Chinese input, there should be no space between words or characters, and each sentence should end with a punctuation mark such as a comma, period, question mark, or exclamation mark. You do not need to add punctuation marks, as we will manually add appropriate ones, but there should be no spaces!

中文字体输入(字与字)之间是不能有空格的，一句话完成后会有(标点符号，例: ， 。 ？ ！这4个是最常用的)，当然你不用加标点符号，因为我们会手动加上合适的符号。但不能有空格！
