### ISSUE TITLE
Language name not visible

### ISSUE THREAD

**Issue by sandoxy** [ElishaAz/Sayboard#70] opened 2024-03-29 07:26 UTC
Hi,

I use three languages within sayboard. But for some time, maybe after the update, sayboard doesn't show me the name of the used language. See the screenshot.
Thanks![Screenshot_2024-03-29.jpg](https://github.com/ElishaAz/Sayboard/assets/38521726/e1968f16-a4fb-4a21-88cd-86e7fc681496)

**Comment by secretServant** [comment] 2024-04-11 18:19
I second this, might also be something to tack onto the ticket for localization #41. If you have three or more models it's like playing roulette. Pretty strange to be able to switch language models but not know at a glance. Currently it is ordered as a list by the models in Sayboard's main menu, just realized they can be clicked and dragged for priority. The problem is that this isn't apparent to the user. 

Overall,  the problem could be solved by having Sayboard provide a list of models when clicking the 'globe' key, rather than iterating through the model list as it currently does. Adding a piece of text for current language when model is loaded would also be useful. "Say something" and "Preparing the recognizer" should both be translated to the language model in use.

**Comment by ElishaAz** [comment] 2024-04-12 09:35
Fixed by e48deda438c121d2a1c7308c23fa65896aa6d2ff

**Closed by ElishaAz** 2024-04-12 09:35 UTC

**Comment by sandoxy** [comment] 2024-06-03 08:44
Don't know, how the current solution looks like, but i've got an idea. For somebody, who is using three or more languages it's not very convenient to click on the globe and then to choose the language. It would probably be better to have on the bottom the keys with the country keywords, for example DE, EN, ...
